volumes:
  media:
  pg_data:
  static:
services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    container_name: foodgram-front
    image: walrus911/frontend_food
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      - ../frontend/:/app/result_build/
  backend:
    container_name: foodgram-backend
    env_file: .env
    build: ../backend/
    volumes:
      - media:/app/media/
      - static:/static/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media
      - static:/static
